export const SVG_NAME = 'wave-svg'
export const WRAP_CLASS = 'wavy-svg-wrap'
export const STOP_CLASS = 'wavy-svg-stop'
export const SVG_MAIN_CLASS = 'wavy-svg-container'
export const SVG_BASE_CLASS = 'wavy-svg-container-base'
